name: basiliskii # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Classic Macintosh emulator using 680x0 CPUs
description: |
  Classic Macintosh emulator using 680x0 CPUs

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  Basilisk.png
title: BasiliskII

apps:
  basiliskii:
    command: BasiliskII-x86_64
parts:
  basiliskii:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      basiliskii: build/
      basiliskii.1: man/man1/

architectures:
  - build-on: amd64

